version: '3.4'

services:
  hub:
    image: hub
    build:
      context: hub
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
